# Generated by Django 5.2 on 2025-04-12 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tx_ref', 'booking')},
        ),
    ]
